[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = [
  "generated.nix"
]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.json",
  "*.yaml",
  "*.md",
]
excludes = [
  "generated.json"
]

[formatter.shell]
command = "shfmt"
options = [
  "-s",
  "-w",
  "-i",
  "2",
]
includes = [
  "*.sh"
]
