# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "lab-${version}";
  version = "0.11.1";
  rev = "v${version}";

  goPackagePath = "github.com/zaquestion/lab";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/zaquestion/lab.git";
    sha256 = "0m997raspr9hc46lzgwv9py4rdmn5813spvks4ns46rjw1107sdw";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    description = "Lab wraps Git or Hub, making it simple to clone, fork, and interact with repositories on GitLab";
    license = licenses.unlicense;
    homepage = https://zaquestion.github.io/lab/;
    maintainers = with maintainers; rummik;
    platforms = with platforms; unix;
  };
}
