# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "c8536fa43f0e8b506e9dd1a91e2f01ceccca0251";
    src = fetchgit {
      url = "https://github.com/haslersn/any-nix-shell";
      rev = "c8536fa43f0e8b506e9dd1a91e2f01ceccca0251";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dQd1/RYH/j3R7MgMoz3EZ2Nxf3XXYCTKxBvi+cvyV2g=";
    };
    date = "2022-12-11";
  };
  bufferline-nvim = {
    pname = "bufferline-nvim";
    version = "v4.3.0";
    src = fetchgit {
      url = "https://github.com/akinsho/bufferline.nvim";
      rev = "v4.3.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-0BJXUDGeUhPALEnPgO4ix+GgI/3P/Foiqi0tf2mgUXg=";
    };
  };
  dug = {
    pname = "dug";
    version = "86fdc610da39f65d2ce24f4a4879f754e2035bd4";
    src = fetchgit {
      url = "https://gitlab.com/rummik/zsh/dug";
      rev = "86fdc610da39f65d2ce24f4a4879f754e2035bd4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-CxJC48Iy0t1gNxMg2ERYSieJCp1ek7xYydik1rwH2Cw=";
    };
    date = "2019-03-25";
  };
  fast-syntax-highlighting = {
    pname = "fast-syntax-highlighting";
    version = "cf318e06a9b7c9f2219d78f41b46fa6e06011fd9";
    src = fetchgit {
      url = "https://github.com/zdharma-continuum/fast-syntax-highlighting";
      rev = "cf318e06a9b7c9f2219d78f41b46fa6e06011fd9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-RVX9ZSzjBW3LpFs2W86lKI6vtcvDWP6EPxzeTcRZua4=";
    };
    date = "2023-07-05";
  };
  flutter-tools-nvim = {
    pname = "flutter-tools-nvim";
    version = "v1.3.1";
    src = fetchgit {
      url = "https://github.com/akinsho/flutter-tools.nvim";
      rev = "v1.3.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-eX24uvO75xgbgCBUyCdy4WRRXnuFYhvM4f2GOUmFPn0=";
    };
  };
  foreign-env = {
    pname = "foreign-env";
    version = "7f0cf099ae1e1e4ab38f46350ed6757d54471de7";
    src = fetchgit {
      url = "https://github.com/oh-my-fish/plugin-foreign-env";
      rev = "7f0cf099ae1e1e4ab38f46350ed6757d54471de7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-4+k5rSoxkTtYFh/lEjhRkVYa2S4KEzJ/IJbyJl+rJjQ=";
    };
    date = "2023-08-23";
  };
  gh-dash = {
    pname = "gh-dash";
    version = "v3.11.0";
    src = fetchFromGitHub {
      owner = "dlvhdr";
      repo = "gh-dash";
      rev = "v3.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-XvNc68pVwqBLthkr3jb578Avpnr1NKT1XWUD4aazBHw=";
    };
  };
  home-assistant-desktop = {
    pname = "home-assistant-desktop";
    version = "ec49f76c2abf450de94cf5ced17358177a2f1649";
    src = fetchFromGitHub {
      owner = "iprodanovbg";
      repo = "homeassistant-desktop";
      rev = "ec49f76c2abf450de94cf5ced17358177a2f1649";
      fetchSubmodules = false;
      sha256 = "sha256-Fu54mGYkJn92803QJOOkyL63I1yGi30OFWTEi1Y2IcM=";
    };
    date = "2023-02-09";
  };
  ing = {
    pname = "ing";
    version = "dc75a8b7ae625c3da73e44c2d52a583790b76938";
    src = fetchgit {
      url = "https://gitlab.com/rummik/zsh/ing";
      rev = "dc75a8b7ae625c3da73e44c2d52a583790b76938";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-c8cCrB2kbJpDP15soVvfurG27NXfqTXDB0LYrWLLRGM=";
    };
    date = "2022-11-15";
  };
  isup = {
    pname = "isup";
    version = "9f34b8dc1fe7641cf4d2dbe7fb5d7d1a297353c7";
    src = fetchgit {
      url = "https://gitlab.com/rummik/zsh/isup";
      rev = "9f34b8dc1fe7641cf4d2dbe7fb5d7d1a297353c7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dCh3MqsWYs9BmLxYQr2i3HearUdSkj7CZMaig6/SPAc=";
    };
    date = "2022-11-15";
  };
  lspsaga-nvim = {
    pname = "lspsaga-nvim";
    version = "32c1b404489723771d385579d695b61cf12bf3a4";
    src = fetchgit {
      url = "https://github.com/nvimdev/lspsaga.nvim";
      rev = "32c1b404489723771d385579d695b61cf12bf3a4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-8l9VX09Pii1Z1hQT7/hOe+3fEFug1v/WZ7rUkIEQjsQ=";
    };
    date = "2023-09-15";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchgit {
      url = "https://github.com/mlvzk/manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    };
    date = "2021-04-20";
  };
  nanosvg-fltk = {
    pname = "nanosvg-fltk";
    version = "abcd277ea45e9098bed752cf9c6875b533c0892f";
    src = fetchFromGitHub {
      owner = "fltk";
      repo = "nanosvg";
      rev = "abcd277ea45e9098bed752cf9c6875b533c0892f";
      fetchSubmodules = false;
      sha256 = "sha256-WNdAYu66ggpSYJ8Kt57yEA4mSTv+Rvzj9Rm1q765HpY=";
    };
    date = "2022-12-22";
  };
  nvim-session-manager = {
    pname = "nvim-session-manager";
    version = "df544e17798dd0e6e33ecf0991dfde9174367837";
    src = fetchgit {
      url = "https://github.com/Shatur/neovim-session-manager";
      rev = "df544e17798dd0e6e33ecf0991dfde9174367837";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-9z974T4Wu0+WXnrrijS9ySZNWCF/s8588k9lBGhg0/k=";
    };
    date = "2023-09-05";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "794266a4edc8ab57b0d637626f01b5278a9123d8";
    src = fetchgit {
      url = "https://github.com/nvim-treesitter/nvim-treesitter";
      rev = "794266a4edc8ab57b0d637626f01b5278a9123d8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/eMyqR8r8oSaG3Ir95u6QRxhfScuLua8KXk+SVFSXEA=";
    };
    date = "2023-09-16";
  };
  nvim-treesitter-textobjects = {
    pname = "nvim-treesitter-textobjects";
    version = "bd103502252027434ec42f628d2dbf54821d4ce6";
    src = fetchgit {
      url = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects";
      rev = "bd103502252027434ec42f628d2dbf54821d4ce6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-bC3yXw0qbcojHNy0peObGUK9DD047CqOAiQ8soEAHww=";
    };
    date = "2023-08-29";
  };
  pass-secret-service = {
    pname = "pass-secret-service";
    version = "fadc09be718ae1e507eeb8719f3a2ea23edb6d7a";
    src = fetchgit {
      url = "https://github.com/mdellweg/pass_secret_service";
      rev = "fadc09be718ae1e507eeb8719f3a2ea23edb6d7a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lrNU5bkG4/fMu5rDywfiI8vNHyBsMf/fiWIeEHug03c=";
    };
    date = "2022-07-18";
  };
  please = {
    pname = "please";
    version = "ccd5ee46dd43aa598b7ce530719d38d44f0ff8bd";
    src = fetchgit {
      url = "https://gitlab.com/rummik/zsh/please";
      rev = "ccd5ee46dd43aa598b7ce530719d38d44f0ff8bd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-+1Hxt2cOs9U26qU47LsPIIDgFaPj2IUjTNdchNr1RAc=";
    };
    date = "2022-11-15";
  };
  prusa-slicer = {
    pname = "prusa-slicer";
    version = "49306cdfce36d9c011f39427856873b9c5b04aeb";
    src = fetchFromGitHub {
      owner = "prusa3d";
      repo = "PrusaSlicer";
      rev = "49306cdfce36d9c011f39427856873b9c5b04aeb";
      fetchSubmodules = false;
      sha256 = "sha256-U0INHNchtEHWir12ueLU/2WGshfWM1GTG1NQ0MomPzA=";
    };
    date = "2023-09-11";
  };
  prusa-wxwidgets = {
    pname = "prusa-wxwidgets";
    version = "cda21c8ddc3b96e2e7ec7955840bc2db34684d2d";
    src = fetchFromGitHub {
      owner = "prusa3d";
      repo = "wxWidgets";
      rev = "cda21c8ddc3b96e2e7ec7955840bc2db34684d2d";
      fetchSubmodules = false;
      sha256 = "sha256-ZC4n0D4mObfBbDLbg4uwxuYga+dmEwB8ZN5BvidXGkg=";
    };
    date = "2020-12-01";
  };
  slowcat = {
    pname = "slowcat";
    version = "f089130d881cef04f46a13322c7998d5aaa4201b";
    src = fetchgit {
      url = "https://gitlab.com/rummik/zsh/slowcat";
      rev = "f089130d881cef04f46a13322c7998d5aaa4201b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Il/hrzRgG92bDX5cxQ7RdeLsjNWBHEtLm67LaoL1P38=";
    };
    date = "2017-11-23";
  };
  tailf = {
    pname = "tailf";
    version = "92b04527b784a70a952efde20e6a7269278fb17d";
    src = fetchgit {
      url = "https://gitlab.com/rummik/zsh/tailf";
      rev = "92b04527b784a70a952efde20e6a7269278fb17d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-JFmTFVLAMABg000jfYsTf42tVjiETi9OZBRI0Yr8B3w=";
    };
    date = "2017-11-30";
  };
  vim-just = {
    pname = "vim-just";
    version = "927b41825b9cd07a40fc15b4c68635c4b36fa923";
    src = fetchgit {
      url = "https://github.com/NoahTheDuke/vim-just";
      rev = "927b41825b9cd07a40fc15b4c68635c4b36fa923";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-BmxYWUVBzTowH68eWNrQKV1fNN9d1hRuCnXqbEagRoY=";
    };
    date = "2023-08-02";
  };
  vim-nix = {
    pname = "vim-nix";
    version = "0def8020f152a51c011a707680780dac61a8989a";
    src = fetchgit {
      url = "https://github.com/rummik/vim-nix";
      rev = "0def8020f152a51c011a707680780dac61a8989a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Q+Jx6/MgeE2hsd/a6FqfXpAOaRcNymZW6t75hYCcH4E=";
    };
    date = "2022-11-16";
  };
  vim-workspace = {
    pname = "vim-workspace";
    version = "c0d1e4332a378f58bfdf363b4957168fa78e79b4";
    src = fetchgit {
      url = "https://github.com/thaerkh/vim-workspace";
      rev = "c0d1e4332a378f58bfdf363b4957168fa78e79b4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2Brx098dk5THiieBiW71FG9mUUwS1CSY9mpOPWA/Tq4=";
    };
    date = "2023-05-28";
  };
  wakatime-zsh-plugin = {
    pname = "wakatime-zsh-plugin";
    version = "69c6028b0c8f72e2afcfa5135b1af29afb49764a";
    src = fetchgit {
      url = "https://github.com/sobolevn/wakatime-zsh-plugin";
      rev = "69c6028b0c8f72e2afcfa5135b1af29afb49764a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-pA1VOkzbHQjmcI2skzB/OP5pXn8CFUz5Ok/GLC6KKXQ=";
    };
    file = "wakatime.plugin.zsh";
    date = "2022-04-27";
  };
  zsh-autocomplete = {
    pname = "zsh-autocomplete";
    version = "afc5afd15fe093bfd96faa521abe0255334c85b0";
    src = fetchgit {
      url = "https://github.com/marlonrichert/zsh-autocomplete";
      rev = "afc5afd15fe093bfd96faa521abe0255334c85b0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-npflZ7sr2yTeLQZIpozgxShq3zbIB5WMIZwMv8rkLJg=";
    };
    date = "2023-08-28";
  };
  zsh-autosuggestions = {
    pname = "zsh-autosuggestions";
    version = "c3d4e576c9c86eac62884bd47c01f6faed043fc5";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-autosuggestions";
      rev = "c3d4e576c9c86eac62884bd47c01f6faed043fc5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-B+Kz3B7d97CM/3ztpQyVkE6EfMipVF8Y4HJNfSRXHtU=";
    };
    date = "2023-09-07";
  };
  zsh-completions = {
    pname = "zsh-completions";
    version = "07fe4030a6a830f394593a78f495db41b0427fa6";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-completions";
      rev = "07fe4030a6a830f394593a78f495db41b0427fa6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xyXMwhyj03CvnLcjyrF0yKuybgNR/kBoekgm7A7+6WI=";
    };
    date = "2023-09-15";
  };
  zsh-theme-rummik = {
    pname = "zsh-theme-rummik";
    version = "c79cec00cb3e01f5be3ec028ca847a1fa5094e0e";
    src = fetchgit {
      url = "https://gitlab.com/rummik/zsh/theme";
      rev = "c79cec00cb3e01f5be3ec028ca847a1fa5094e0e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-fHckfslHAFQHANT1wcn/HCpWmXW4XOp+eRjLnl/bP4Y=";
    };
    file = "rummik.zsh-theme";
    date = "2019-10-24";
  };
  zsh-vi-mode = {
    pname = "zsh-vi-mode";
    version = "1f28e1886dc8e49f41b817634d5c7695b6abb145";
    src = fetchgit {
      url = "https://github.com/jeffreytse/zsh-vi-mode";
      rev = "1f28e1886dc8e49f41b817634d5c7695b6abb145";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ylkZ4oVRxBJbk6tJ6UxkDjS+5eCr7efezuTrz8OZm+4=";
    };
    date = "2023-07-26";
  };
}
