# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "67d8b02e605684c46a12445e689cda0c88fe278e";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "67d8b02e605684c46a12445e689cda0c88fe278e";
      fetchSubmodules = false;
      sha256 = "sha256-y9oOn1pDVPcY1ttWlTBZVptavgTwGQbADWpwe4yZG04=";
    });
  };
  grep-vim = {
    pname = "grep-vim";
    version = "852ddb0c6590bbc41c508d7f5d2fc17112492def";
    src = fetchFromGitHub ({
      owner = "vim-scripts";
      repo = "grep.vim";
      rev = "852ddb0c6590bbc41c508d7f5d2fc17112492def";
      fetchSubmodules = false;
      sha256 = "sha256-I9uhavui6TwlPkPoWmqcZpx+SjKMiaOxJz4jnCkk6go=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  nvim-session-manager = {
    pname = "nvim-session-manager";
    version = "24ceb4bfe666ca74f52ed3821a9f778c6324a84b";
    src = fetchFromGitHub ({
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "24ceb4bfe666ca74f52ed3821a9f778c6324a84b";
      fetchSubmodules = false;
      sha256 = "sha256-iuADiGQ1fJLu8JAuHnSFUExfI6fGBMm+NV+HycIcLXg=";
    });
  };
  vader-vim = {
    pname = "vader-vim";
    version = "6fff477431ac3191c69a3a5e5f187925466e275a";
    src = fetchFromGitHub ({
      owner = "junegunn";
      repo = "vader.vim";
      rev = "6fff477431ac3191c69a3a5e5f187925466e275a";
      fetchSubmodules = false;
      sha256 = "sha256-k9d1R/QDzthHs11GywBM1JcfOs+LnIGyp4UXl2vIbJQ=";
    });
  };
  vim-coloresque = {
    pname = "vim-coloresque";
    version = "e12a5007068e74c8ffe5b1da91c25989de9c2081";
    src = fetchFromGitHub ({
      owner = "gko";
      repo = "vim-coloresque";
      rev = "e12a5007068e74c8ffe5b1da91c25989de9c2081";
      fetchSubmodules = false;
      sha256 = "sha256-b8EYF/CYhz6qDmhybNJUVyXmbSfEOap01wP4SwuANRY=";
    });
  };
  vim-css3-syntax = {
    pname = "vim-css3-syntax";
    version = "f6dde98e899927473aba1d30667391a181490ad6";
    src = fetchFromGitHub ({
      owner = "hail2u";
      repo = "vim-css3-syntax";
      rev = "f6dde98e899927473aba1d30667391a181490ad6";
      fetchSubmodules = false;
      sha256 = "sha256-nlK6ovnkJ6eZD03KpQjOqlXXHTmcQvSZjl70onfOKWc=";
    });
  };
  vim-js = {
    pname = "vim-js";
    version = "90f340d31907590fad059cd9aab03a55ab49e352";
    src = fetchFromGitHub ({
      owner = "yuezk";
      repo = "vim-js";
      rev = "90f340d31907590fad059cd9aab03a55ab49e352";
      fetchSubmodules = false;
      sha256 = "sha256-SjBnT5Dh1FlcN89cf9NFTYMCCMNatje9EisYiAvPZ4A=";
    });
  };
  vim-just = {
    pname = "vim-just";
    version = "838c9096d4c5d64d1000a6442a358746324c2123";
    src = fetchFromGitHub ({
      owner = "NoahTheDuke";
      repo = "vim-just";
      rev = "838c9096d4c5d64d1000a6442a358746324c2123";
      fetchSubmodules = false;
      sha256 = "sha256-DSC47z2wOEXvo2kGO5JtmR3hyHPiYXrkX7MgtagV5h4=";
    });
  };
  vim-nix = {
    pname = "vim-nix";
    version = "0def8020f152a51c011a707680780dac61a8989a";
    src = fetchFromGitHub ({
      owner = "rummik";
      repo = "vim-nix";
      rev = "0def8020f152a51c011a707680780dac61a8989a";
      fetchSubmodules = false;
      sha256 = "sha256-Q+Jx6/MgeE2hsd/a6FqfXpAOaRcNymZW6t75hYCcH4E=";
    });
  };
  vim-session = {
    pname = "vim-session";
    version = "9e9a6088f0554f6940c19889d0b2a8f39d13f2bb";
    src = fetchFromGitHub ({
      owner = "xolox";
      repo = "vim-session";
      rev = "9e9a6088f0554f6940c19889d0b2a8f39d13f2bb";
      fetchSubmodules = false;
      sha256 = "sha256-a+yRjpShuMMHspa2VtqkUUlNyR96TiiAKuldDKAb02Q=";
    });
  };
  vim-smali = {
    pname = "vim-smali";
    version = "46d2a7583234bf0819a18d9f73ab8c751d6a58ad";
    src = fetchFromGitHub ({
      owner = "rummik";
      repo = "vim-smali";
      rev = "46d2a7583234bf0819a18d9f73ab8c751d6a58ad";
      fetchSubmodules = false;
      sha256 = "sha256-DRQtBkvfNKb5dLLGG3mesZj4yGm6OSErzB+KjXKUI68=";
    });
  };
  vim-workspace = {
    pname = "vim-workspace";
    version = "c26b473f9b073f24bacecd38477f44c5cd1f5a62";
    src = fetchFromGitHub ({
      owner = "thaerkh";
      repo = "vim-workspace";
      rev = "c26b473f9b073f24bacecd38477f44c5cd1f5a62";
      fetchSubmodules = false;
      sha256 = "sha256-XV7opLyfkHIDO0+JJaO/x0za0gsHuklrzapTGdLHJmI=";
    });
  };
  yajs-vim = {
    pname = "yajs-vim";
    version = "2bebc45ce94d02875803c67033b2d294a5375064";
    src = fetchFromGitHub ({
      owner = "othree";
      repo = "yajs.vim";
      rev = "2bebc45ce94d02875803c67033b2d294a5375064";
      fetchSubmodules = false;
      sha256 = "sha256-gN1Ji2/ApqJRHc1FNu+N7xegifKnQpGwTIqDvSwZfpY=";
    });
  };
}
