# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "67d8b02e605684c46a12445e689cda0c88fe278e";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "67d8b02e605684c46a12445e689cda0c88fe278e";
      fetchSubmodules = false;
      sha256 = "sha256-y9oOn1pDVPcY1ttWlTBZVptavgTwGQbADWpwe4yZG04=";
    });
    date = "2022-01-31";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  nvim-session-manager = {
    pname = "nvim-session-manager";
    version = "24ceb4bfe666ca74f52ed3821a9f778c6324a84b";
    src = fetchFromGitHub ({
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "24ceb4bfe666ca74f52ed3821a9f778c6324a84b";
      fetchSubmodules = false;
      sha256 = "sha256-iuADiGQ1fJLu8JAuHnSFUExfI6fGBMm+NV+HycIcLXg=";
    });
    date = "2022-11-13";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "1821c656d8e42fd8ce6648af58e64268606e8bec";
    src = fetchFromGitHub ({
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "1821c656d8e42fd8ce6648af58e64268606e8bec";
      fetchSubmodules = false;
      sha256 = "sha256-NtHjCiYCVKvp2QCB92kXmvFbuA+4GM965hkFLDdIahY=";
    });
    date = "2022-11-28";
  };
  nvim-treesitter-textobjects = {
    pname = "nvim-treesitter-textobjects";
    version = "98476e7364821989ab9b500e4d20d9ae2c5f6564";
    src = fetchFromGitHub ({
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-textobjects";
      rev = "98476e7364821989ab9b500e4d20d9ae2c5f6564";
      fetchSubmodules = false;
      sha256 = "sha256-0s/omiZhjC93MCTkLqD+lQObcldh6nz8jfkOOhTUc78=";
    });
    date = "2022-11-27";
  };
  pass-secret-service = {
    pname = "pass-secret-service";
    version = "fadc09be718ae1e507eeb8719f3a2ea23edb6d7a";
    src = fetchFromGitHub ({
      owner = "mdellweg";
      repo = "pass_secret_service";
      rev = "fadc09be718ae1e507eeb8719f3a2ea23edb6d7a";
      fetchSubmodules = false;
      sha256 = "sha256-lrNU5bkG4/fMu5rDywfiI8vNHyBsMf/fiWIeEHug03c=";
    });
    date = "2022-07-18";
  };
  vim-just = {
    pname = "vim-just";
    version = "838c9096d4c5d64d1000a6442a358746324c2123";
    src = fetchFromGitHub ({
      owner = "NoahTheDuke";
      repo = "vim-just";
      rev = "838c9096d4c5d64d1000a6442a358746324c2123";
      fetchSubmodules = false;
      sha256 = "sha256-DSC47z2wOEXvo2kGO5JtmR3hyHPiYXrkX7MgtagV5h4=";
    });
    date = "2022-11-02";
  };
  vim-nix = {
    pname = "vim-nix";
    version = "0def8020f152a51c011a707680780dac61a8989a";
    src = fetchFromGitHub ({
      owner = "rummik";
      repo = "vim-nix";
      rev = "0def8020f152a51c011a707680780dac61a8989a";
      fetchSubmodules = false;
      sha256 = "sha256-Q+Jx6/MgeE2hsd/a6FqfXpAOaRcNymZW6t75hYCcH4E=";
    });
    date = "2022-11-16";
  };
  vim-workspace = {
    pname = "vim-workspace";
    version = "c26b473f9b073f24bacecd38477f44c5cd1f5a62";
    src = fetchFromGitHub ({
      owner = "thaerkh";
      repo = "vim-workspace";
      rev = "c26b473f9b073f24bacecd38477f44c5cd1f5a62";
      fetchSubmodules = false;
      sha256 = "sha256-XV7opLyfkHIDO0+JJaO/x0za0gsHuklrzapTGdLHJmI=";
    });
    date = "2021-11-25";
  };
}
